# Perfil QA — desarrollo / ambiente de pruebas
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.cinebook: DEBUG

management:
  endpoint:
    health:
      show-details: always
