cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cinebook
    username: cinebook
    password: cinebook
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 120000
      maximum-pool-size: 5
